config/routes.rb
ISver2::Application.routes.draw do
  resources :sold_items

  resources :suppliers

  resources :sales

  resources :products

  resources :searches

  root to: 'sales#index'

end

app/models/sold_item.rb
class SoldItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
  accepts_nested_attributes_for :product, :sale

  def sales
    @sales ||= find_sales
  end

  private

  def find_sales
    sales = sales.where("date >= ?", start_date)
    sales = sales.where("date <= ?", end_date)
    sales
  end



end

app/controllers/sold_items_controller.rb
class SoldItemsController < ApplicationController
  before_action :set_sold_item, only: [:show, :edit, :update, :destroy]

  # GET /sold_items
  # GET /sold_items.json
  def index
    @sold_items = SoldItem.all
  end

  # GET /sold_items/1
  # GET /sold_items/1.json
  def show
    @sold_item = SoldItem.find(params[:start_date, :end_date])
  end

  # GET /sold_items/new
  def new
    @sold_item = SoldItem.new
  end

  # GET /sold_items/1/edit
  def edit
  end

  # POST /sold_items
  # POST /sold_items.json
  def create
    @sold_item = SoldItem.create!(params[:start_date, :end_date])
    redirect_to @sold_item

    #respond_to do |format|
    #  if @sold_item.save
    #    format.html { redirect_to @sold_item, notice: 'Sold item was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @sold_item }
    #  else
    #    format.html { render action: 'new' }
    #    format.json { render json: @sold_item.errors, status: :unprocessable_entity }
     # end
   # end
  end

  # PATCH/PUT /sold_items/1
  # PATCH/PUT /sold_items/1.json
  def update
    respond_to do |format|
      if @sold_item.update(sold_item_params)
        format.html { redirect_to @sold_item, notice: 'Sold item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sold_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sold_items/1
  # DELETE /sold_items/1.json
  def destroy
    @sold_item.destroy
    respond_to do |format|
      format.html { redirect_to sold_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sold_item
      @sold_item = SoldItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sold_item_params
      params.require(:sold_item).permit(:sale_id, :product_id, :start_date, :end_date)
    end
end

app/helpers/sold_items_helper.rb
module SoldItemsHelper
end

app/views/sold_items/_form.html.erb
<%= form_for(@sold_item) do |f| %>
  <% if @sold_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sold_item.errors.count, "error") %> prohibited this sold_item from being saved:</h2>

      <ul>
      <% @sold_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sold_items/edit.html.erb
<h1>Editing sold_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @sold_item %> |
<%= link_to 'Back', sold_items_path %>

app/views/sold_items/index.html.erb
<h1>Listing sold_items</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>
      <th>Product</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sold_items.each do |sold_item| %>
      <tr>
        <td><%= sold_item.sale_id %></td>
        <td><%= sold_item.product_id %></td>
        <td><%= sold_item.start_date %></td>
        <td><%= sold_item.end_date %></td>
        <td><%= link_to 'Show', sold_item %></td>
        <td><%= link_to 'Edit', edit_sold_item_path(sold_item) %></td>
        <td><%= link_to 'Destroy', sold_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sold item', new_sold_item_path %>
<%= link_to 'New Sold item', report_sold_item_path %>

app/views/sold_items/new.html.erb
<h1>New sold_item</h1>

<%= render 'form' %>

<%= link_to 'Back', sold_items_path %>

app/views/sold_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale:</strong>
  <%= @sold_item.sale_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @sold_item.product_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @sold_item.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @sold_item.end_date %>
</p>

<%= link_to 'Edit', edit_sold_item_path(@sold_item) %> |
<%= link_to 'Back', sold_items_path %>