config/routes.rb
ISver2::Application.routes.draw do
  resources :sold_items

  resources :suppliers

  resources :sales

  resources :products

  resources :searches

  root to: 'sales#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :sales
  has_many :searches
  has_many :suppliers

  validates_presence_of :name, :qty
  validates_uniqueness_of :name
  validates_numericality_of :qty, :greater_than_or_equal_to => 0, :only_integer => true

  def self.search_min_quantity(query)
    where("qty <= ?",  "#{query}")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:qty_search]
      @products = Product.search_min_quantity(params[:qty_search]).order("qty DESC")
    else
    @products = Product.all
    end
  end

  def stock

  end
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :qty)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Product Name" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :qty, "Product Qty" %>
    <%= f.number_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Product and Inventory Management</h1>
<%= link_to 'New Product Inventory', new_product_path %>
<hr>
<style>
table, td, th
{
border:1px solid teal;
}
th
{
background-color:teal;
color:lightgrey;
}

th, td
{
    padding:15px;
}
</style>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Qty</th>

      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.qty %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Generate Report for Low Inventory Items</h2>
<%= form_tag(products_path, :method => "get", id: "search-form") do %>
    Enter Minimum Product Quantity: <br />
    <%= text_field_tag :qty_search, params[:qty_search], placeholder: "enter an integer" %>
    <%= submit_tag "Search", :product_name => nil %>
<% end %>
<%= link_to 'Go Back', products_path %>

app/views/products/new.html.erb
<h1>New Inventory Product</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @product.qty %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/stock.html.erb
<h1>Product and Inventory Management</h1>
<%= link_to 'New Product Inventory', new_product_path %>
<hr>
<style>
    table, td, th
    {
        border:1px solid teal;
    }
    th
    {
        background-color:teal;
        color:lightgrey;
    }

    th, td
    {
        padding:15px;
    }
</style>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Qty</th>

    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.qty %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>