config/routes.rb
ISver2::Application.routes.draw do
  resources :sold_items

  resources :suppliers

  resources :sales

  resources :products

  resources :searches

  root to: 'sales#index'

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  belongs_to :product

  validates_presence_of :product_id, :date_r, :qty_r
  validates_numericality_of :qty_r, :greater_than_or_equal_to => 1, :only_integer => true

  after_create :update_product_qty

  def update_product_qty
    self.product.update_attribute("qty", (product.qty + self.qty_r))
  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supplier }
      else
        format.html { render action: 'new' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:product_id, :date_r, :qty_r)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_for(@supplier) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.collection_select :product_id, Product.all, :id, :name, :prompt_text => true %>
  </div>
  <div class="field">
    <%= f.label :date_r, "Date Received"%>
    <%= f.date_select :date_r, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :qty_r, "Quantity Received" %>
    <%= f.number_field :qty_r %>
  </div>
  <div class="actions">
    <%= f.submit "Add Product Inventory" %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<h1>Product Suppliers</h1>
<hr>
<style>
    table, td, th
    {
        border:1px solid teal;
    }
    th
    {
        background-color:teal;
        color:lightgrey;
    }

    th, td
    {
        padding:15px;
    }
</style>
<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Date Received</th>
      <th>Qty Received</th>
      <th></th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.product.name %></td>
        <td><%= supplier.date_r %></td>
        <td><%= supplier.qty_r %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Product Received', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Add Product and Quantity Received by Supplier</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @supplier.product.name %>
</p>

<p>
  <strong>Date Recieved:</strong>
  <%= @supplier.date_r %>
</p>

<p>
  <strong>Qty Recieved:</strong>
  <%= @supplier.qty_r %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>