config/routes.rb
ISver2::Application.routes.draw do
  resources :sold_items

  resources :suppliers

  resources :sales

  resources :products

  resources :searches

  root to: 'sales#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  validates_presence_of :product_id, :date, :price, :qty
  validates_numericality_of :qty, :greater_than_or_equal_to => 1, :only_integer => true
  validates_numericality_of :qty, :less_than_or_equal_to => Proc.new {|sale|sale.product.qty}, :message => "Not enough quantity in stock, please modify selected quantity"
  validates_numericality_of :price, :greater_than_or_equal_to => 0.01


  belongs_to :product
  has_many :searches
  accepts_nested_attributes_for :product

  before_create :calculate_total

  def calculate_total
    self.total = self.qty * self.price
  end

  after_create :reduce_product_qty

  def reduce_product_qty
    self.product.update_attribute("qty", (product.qty - self.qty))
  end

  def self.search(query)
    where("sale_id >= ?", "%#{query}%")
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    #@sales = Sale.search(params[:search])
    if params[:search]
      @sales = Sale.search(params[:search])
    end
    @sales = Sale.all

  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  def report
    @sale = Sale.report
  end
  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:product_id, :date, :qty, :price, :total)
    end


end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
    <% if @sale.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

          <ul>
            <% @sale.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :product_id, "Select Product"%><br>
      <%= f.collection_select :product_id, Product.all, :id, :name, :prompt_text => true %>
    </div>
    <div class="field">
      <%= f.label :date, "Date of Sale"%><br>
      <%= f.date_select :date, :order => [:month, :day, :year] %>
    </div>
    <div class="field">
      <%= f.label :qty, "Qty Sold"%><br>
      <%= f.number_field :qty %>
    </div>
    <div class="field">
      <%= f.label :price, "Unit Price" %><br>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :total %>
      <%= f.hidden_field :total %>
      will be calculated when submitted
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Sales Transactions</h1>
<%= link_to 'Add New Sale', new_sale_path %>
<%= link_to "View Product Inventory", products_path %>
<%= link_to "Advanced Search", new_sold_item_path %>

<hr>
<style>
    table, td, th
    {
        border:1px solid teal;
    }
    th
    {
        background-color:teal;
        color:lightgrey;
    }

    th, td
    {
        padding:15px;
    }
</style>
<br>
<table>
  <thead>
  <tr>
    <th>Product</th>
    <th>Date</th>
    <th>Qty</th>
    <th>Price</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @sales.each do |sale|  %>
      <tr>

        <td><%= sale.product.name %></td>
        <td><%= sale.date %></td>
        <td><%= sale.qty %></td>
        <td><%= number_to_currency(sale.price) %></td>
        <td><%= number_to_currency(sale.total) %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br><br>
<table>
  <thead>
  <tr>
    <th>Total Qty Sold</th>
    <th>Average Total</th>
    <th>Total Sales</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= Sale.sum(:qty) %></td>
    <td><%= number_to_currency(Sale.average(:total)) %></td>
    <td><%= number_to_currency(Sale.sum(:total))%></td>
  </tr>
  </tbody>
</table>

app/views/sales/new.html.erb
<h1>Add New Sale Transaction</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/report.html.erb
<table>
  <thead>
  <tr>
    <th>Product</th>
    <th>Date</th>
    <th>Qty</th>
    <th>Price</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @sales.each do |sale|  %>
      <tr>

        <td><%= sale.product.name %></td>
        <td><%= sale.date %></td>
        <td><%= sale.qty %></td>
        <td><%= number_to_currency(sale.price) %></td>
        <td><%= number_to_currency(sale.total) %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Total Qty Sold</p>
<p><%= Sale.sum(:qty) %></p>
<p> Average Total</p>
<p><%= number_to_currency(Sale.average(:total)) %></p>
<br>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @sale.product.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @sale.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@sale.price) %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@sale.total) %>
</p>
<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>